# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: golang
dist: bionic

services:
  - docker

go:
  - 1.16

env:
  global:
  - PROTOBUF_VERSION=3.11.4
  - PATH="$PATH:$HOME/protoc/bin:$HOME/go/bin"

before_install:
  - curl -L https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - go get -v github.com/golang/protobuf/protoc-gen-go
  - go get -v github.com/golang/mock/mockgen

script:
  - make -j2 all build-image

after_success:
  - bash <(curl -s https://codecov.io/bash)
