# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

namespace: csi-sanlock-lvm-system

# Commented due to https://github.com/kubernetes-sigs/kustomize/issues/677
#commonLabels:
#  app: csi-sanlock-lvm

resources:
  - crd-snapshot.storage.k8s.io_volumesnapshotclasses.url.yaml
  - crd-snapshot.storage.k8s.io_volumesnapshotcontents.url.yaml
  - crd-snapshot.storage.k8s.io_volumesnapshots.url.yaml
  - csi-sanlock-lvm-attacher.var.yaml
  - csi-sanlock-lvm-driverinfo.var.yaml
  - csi-sanlock-lvm-plugin.var.yaml
  - csi-sanlock-lvm-provisioner.var.yaml
  - csi-sanlock-lvm-resizer.var.yaml
  - csi-sanlock-lvm-snapshotter.var.yaml
  - rbac-attacher.url.yaml
  - rbac-provisioner.url.yaml
  - rbac-resizer.url.yaml
  - rbac-snapshot-controller.url.yaml
  - rbac-snapshotter.url.yaml
  - setup-snapshot-controller.url.yaml
  - csi-sanlock-lvm-networkpolicy.var.yaml
